# Generated by Django 4.1.5 on 2023-02-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_housetype_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(default='', verbose_name='описание')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.room')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.housetype')),
            ],
        ),
    ]
