# Generated by Django 4.1.5 on 2023-02-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_myblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ['-created_at']},
        ),
    ]
