# Generated by Django 4.1.5 on 2023-02-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('year_birth', models.IntegerField(max_length=4, verbose_name='год рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('isbn', models.IntegerField(max_length=30, verbose_name='международный номер')),
                ('year', models.IntegerField(max_length=4, verbose_name='год выпуска')),
                ('pages', models.IntegerField(max_length=10, verbose_name='количество страниц')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new_app_goods.author')),
            ],
        ),
    ]
