# Generated by Django 4.1.5 on 2023-02-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_good_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['count', 'name']},
        ),
    ]
